### ISSUE TITLE
API Key not working with proget v6

### ISSUE THREAD

**Issue by nokinger** [Inedo/Inedo.AssetDirectories#1]
Looks like the API Key Authentication Method did not support the new Proget v6 API. 
In AssetDirectoryClient.cs https://github.com/Inedo/Inedo.AssetDirectories/blob/759f7a0486fa8f14789274a61877bbedb493d39c/Inedo.AssetDirectories/AssetDirectoryClient.cs#L257

headers will be set as : `request.Headers["X-ProGet-ApiKey"] = this.apiKey; `
But i guess new API expects: `request.Headers["X-ApiKey"] = this.apiKey;`

**Comment by gdivis** [comment]
Hi,

Thanks for catching this - it was a late change in v6. We'll fix it both here and in ProGet itself so both headers will be allowed.

**Comment by nokinger** [comment]
I see in youtrack with 6.0.9 this will be fixed. Thats nice, thank you.

But currently i stuck with UploadMultipartFileAsync or UploadFileAsync. It says "Specified method is not supported." When i try to upload a new file. I try this with Proget 6.0.8 Instance running on Linux as Docker Container.

The same code works with a Proget 5.3.16 Instance running on Windows (old Instance for tests). I can not find the reason at the moment. 

Sorry for reuse of this ticket.

**Comment by gdivis** [comment]
Hmm.. That's an unexpected error. We'll see if we can reproduce that one. We did also just fix an issue with uploading assets to an asset directory hosted on Linux ([PG-2105](https://inedo.myjetbrains.com/youtrack/issue/PG-2105)) so it's possible it's related to that.

**Comment by gdivis** [comment]
We've investigated the issue and fixed it as [PG-2109](https://inedo.myjetbrains.com/youtrack/issue/PG-2109). It will also be included in this Friday's release of ProGet 6.0.9.
